server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: Authentication
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 50
      pool-name: postgresDBPool1
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
###swagger
application:
  description: Authentication
  version: 1.0
build.date: 2023-09-23

###Timeout api
rest:
  template:
    read: 30000
    connect: 30000
